name: Publish Website
on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: FTP-Deploy-Action
    steps:
      - name: Checkout master
        uses: actions/checkout@master

      - name: Zip Release
        uses: TheDoctor0/zip-release@v0.2.1
        with:
          path: src
          # List of excluded files/directories

      - name: Make Dir && Move
        run: mkdir temporary && mv release.zip ./temporary

      - name: Ls
        run: ls -al

      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          LOCAL_DIR: temporary
          ARGS: --delete --exclude-glob=uploads/** --exclude=.ftpquota --exclude=index.php --exclude-glob=.git*/** --exclude-glob=.git** --exclude-glob=README*
